In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('kc_house_data.csv')

In [3]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,10/13/2014,221900.0,3,1.00,1180,5650,1.0,NaN,0.0,...,7,1180,0.0,1955,0.0,98178,47.5112,-122.257,1340,5650
1,6414100192,12/9/2014,538000.0,3,2.25,2570,7242,2.0,0.0,0.0,...,7,2170,400.0,1951,1991.0,98125,47.7210,-122.319,1690,7639
2,5631500400,2/25/2015,180000.0,2,1.00,770,10000,1.0,0.0,0.0,...,6,770,0.0,1933,NaN,98028,47.7379,-122.233,2720,8062
3,2487200875,12/9/2014,604000.0,4,3.00,1960,5000,1.0,0.0,0.0,...,7,1050,910.0,1965,0.0,98136,47.5208,-122.393,1360,5000
4,1954400510,2/18/2015,510000.0,3,2.00,1680,8080,1.0,0.0,0.0,...,8,1680,0.0,1987,0.0,98074,47.6168,-122.045,1800,7503

In [5]:
sum(df.id.duplicated())

177

In [8]:
df.loc[df['id'].duplicated(keep = False)] # shows all duplicates - and original to see if they are duplicated across all rows
# looks like some id duplicates have different dates - indicating multiple sales of the same house

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
93,6021501535,7/25/2014,430000.0,3,1.50,1580,5000,1.0,0.0,0.0,...,8,1290,290.0,1939,0.0,98117,47.6870,-122.386,1570,4500
94,6021501535,12/23/2014,700000.0,3,1.50,1580,5000,1.0,0.0,0.0,...,8,1290,290.0,1939,0.0,98117,47.6870,-122.386,1570,4500
313,4139480200,6/18/2014,1380000.0,4,3.25,4290,12103,1.0,0.0,3.0,...,11,2690,1600.0,1997,0.0,98006,47.5503,-122.102,3860,11244
314,4139480200,12/9/2014,1400000.0,4,3.25,4290,12103,1.0,0.0,3.0,...,11,2690,1600.0,1997,0.0,98006,47.5503,-122.102,3860,11244
324,7520000520,9/5/2014,232000.0,2,1.00,1240,12092,1.0,NaN,0.0,...,6,960,280.0,1922,1984.0,98146,47.4957,-122.352,1820,7460
325,7520000520,3/11/2015,240500.0,2,1.00,1240,12092,1.0,0.0,0.0,...,6,960,280.0,1922,1984.0,98146,47.4957,-122.352,1820,7460
345,3969300030,7/23/2014,165000.0,4,1.00,1000,7134,1.0,0.0,0.0,...,6,1000,0.0,1943,0.0,98178,47.4897,-122.240,1020,7138
346,3969300030,12/29/2014,239900.0,4,1.00,1000,7134,1.0,0.0,0.0,...,6,1000,0.0,1943,NaN,98178,47.4897,-122.240,1020,7138
371,2231500030,10/1/2014,315000.0,4,2.25,2180,10754,1.0,NaN,0.0,...,7,1100,1080.0,1954,0.0,98133,47.7711,-122.341,1810,6929
372,2231500030,3/24/2015,530000.0,4,2.25,2180,10754,1.0,0.0,0.0,...,7,1100,1080.0,1954,0.0,98133,47.7711,-122.341,1810,6929
717,8820903380,7/28/2014,452000.0,6,2.25,2660,13579,2.0,0.0,0.0,...,7,2660,0.0,1937,1990.0,98125,47.7142,-122.286,1120,8242
718,8820903380,1/2/2015,730000.0,6,2.25,2660,13579,2.0,0.0,0.0,...,7,2660,0.0,1937,1990.0,98125,47.7142,-122.286,1120,8242
823,726049190,10/2/2014,287500.0,3,1.00,1810,7200,1.0,0.0,0.0,...,7,1130,680.0,1954,0.0,98133,47.7493,-122.351,1810,8100
824,726049190,2/18/2015,431000.0,3,1.00,1810,7200,1.0,NaN,0.0,...,7,1130,680.0,1954,0.0,98133,47.7493,-122.351,1810,8100
836,8682262400,7/18/2014,430000.0,2,1.75,1350,4003,1.0,0.0,0.0,...,8,1350,0.0,2004,0.0,98053,47.7176,-122.033,1350,4479
837,8682262400,5/13/2015,419950.0,2,1.75,1350,4003,1.0,0.0,0.0,...,8,1350,0.0,2004,0.0,98053,47.7176,-122.033,1350,4479
1084,9834200885,7/17/2014,360000.0,4,2.50,2080,4080,1.0,0.0,0.0,...,7,1040,1040.0,1962,0.0,98144,47.5720,-122.290,1340,4080
1085,9834200885,4/20/2015,550000.0,4,2.50,2080,4080,1.0,0.0,0.0,...,7,1040,1040.0,1962,0.0,98144,47.5720,-122.290,1340,4080
1127,8062900070,9/9/2014,272000.0,5,1.50,2550,6300,1.0,0.0,0.0,...,7,1560,990.0,1959,0.0,98056,47.5014,-122.172,1380,6300
1128,8062900070,2/13/2015,369000.0,5,1.50,2550,6300,1.0,0.0,0.0,...,7,1560,990.0,1959,NaN,98056,47.5014,-122.172,1380,6300
1200,1231000510,9/22/2014,263000.0,3,1.75,1490,3800,1.0,0.0,0.0,...,6,700,790.0,1913,0.0,98118,47.5554,-122.270,2180,4000
1201,1231000510,5/4/2015,510000.0,3,1.75,1490,3800,1.0,0.0,0.0,...,6,700,790.0,1913,0.0,98118,47.5554,-122.270,2180,4000
1232,6117501820,6/18/2014,250275.0,2,1.00,790,11234,1.0,0.0,0.0,...,6,790,0.0,1942,0.0,98166,47.4413,-122.349,1930,11871
1233,6117501820,4/28/2015,435000.0,2,1.00,790,11234,1.0,0.0,0.0,...,6,790,0.0,1942,0.0,98166,47.4413,-122.349,1930,11871
1448,2228900270,8/12/2014,215000.0,2,1.00,1010,6000,1.0,0.0,0.0,...,6,1010,0.0,1944,NaN,98133,47.7710,-122.353,1610,7313
1449,2228900270,2/12/2015,302000.0,2,1.00,1010,6000,1.0,NaN,0.0,...,6,1010,0.0,1944,0.0,98133,47.7710,-122.353,1610,7313
1462,3630120700,5/13/2014,757000.0,3,3.25,3190,5283,2.0,0.0,0.0,...,9,3190,0.0,2007,0.0,98029,47.5534,-122.002,2950,5198
1463,3630120700,1/7/2015,765000.0,3,3.25,3190,5283,2.0,0.0,0.0,...,9,3190,0.0,2007,0.0,98029,47.5534,-122.002,2950,5198
1574,7888000390,6/27/2014,140000.0,3,1.00,1060,7473,1.0,0.0,0.0,...,7,1060,0.0,1959,0.0,98198,47.3699,-122.309,1320,7912
1575,7888000390,4/1/2015,235000.0,3,1.00,1060,7473,1.0,0.0,0.0,...,7,1060,0.0,1959,NaN,98198,47.3699,-122.309,1320,7912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18219,6751300375,7/2/2014,415000.0,3,1.00,1520,9030,1.0,0.0,0.0,...,7,1520,0.0,1956,0.0,98007,47.5870,-122.134,1470,8712
18220,6751300375,10/16/2014,522500.0,3,1.00,1520,9030,1.0,0.0,0.0,...,7,1520,0.0,1956,NaN,98007,47.5870,-122.134,1470,8712
18549,7657000540,9/2/2014,165000.0,4,1.00,1220,7980,1.5,0.0,0.0,...,6,1220,0.0,1944,0.0,98178,47.4924,-122.237,1210,7920
18550,7657000540,3/4/2015,260000.0,4,1.00,1220,7980,1.5,0.0,0.0,...,6,1220,0.0,1944,0.0,98178,47.4924,-122.237,1210,7920
18688,3558900590,11/25/2014,360000.0,6,1.75,2230,10080,1.0,0.0,0.0,...,7,1390,840.0,1969,0.0,98034,47.7089,-122.201,2110,8475
18689,3558900590,3/24/2015,692500.0,6,1.75,2230,10080,1.0,0.0,0.0,...,7,1390,840.0,1969,0.0,98034,47.7089,-122.201,2110,8475
18690,8121100395,6/24/2014,425000.0,4,1.50,1600,6180,1.5,0.0,0.0,...,6,1600,0.0,1946,0.0,98118,47.5681,-122.285,1410,6180
18691,8121100395,3/11/2015,645000.0,4,1.50,1600,6180,1.5,0.0,0.0,...,6,1600,0.0,1946,0.0,98118,47.5681,-122.285,1410,6180
18747,3332000615,10/20/2014,310000.0,3,1.00,1330,3740,1.5,0.0,0.0,...,6,1330,0.0,1903,NaN,98118,47.5502,-122.274,1330,5053
18748,3332000615,4/22/2015,389000.0,3,1.00,1330,3740,1.5,NaN,0.0,...,6,1330,0.0,1903,0.0,98118,47.5502,-122.274,1330,5053
18976,7856400300,7/2/2014,1410000.0,2,2.50,3180,9400,2.0,0.0,4.0,...,10,2610,570.0,1985,0.0,98006,47.5617,-122.158,3760,9450
18977,7856400300,3/22/2015,1510000.0,2,2.50,3180,9400,2.0,0.0,4.0,...,10,2610,570.0,1985,0.0,98006,47.5617,-122.158,3760,9450
19194,1901600090,6/26/2014,359000.0,5,1.75,1940,6654,1.5,0.0,0.0,...,7,1940,0.0,1953,0.0,98166,47.4663,-122.359,2300,9500
19195,1901600090,4/26/2015,390000.0,5,1.75,1940,6654,1.5,NaN,0.0,...,7,1940,0.0,1953,0.0,98166,47.4663,-122.359,2300,9500
19320,6021500970,5/28/2014,345000.0,2,1.00,1080,4000,1.0,0.0,0.0,...,7,1080,0.0,1940,0.0,98117,47.6902,-122.387,1530,4240
19321,6021500970,4/7/2015,874950.0,2,1.00,1080,4000,1.0,0.0,0.0,...,7,1080,?,1940,NaN,98117,47.6902,-122.387,1530,4240
19536,643300040,11/4/2014,481000.0,4,1.75,1920,9500,1.0,0.0,0.0,...,7,1470,450.0,1966,0.0,98006,47.5683,-122.177,1820,10091
19537,643300040,3/13/2015,719521.0,4,1.75,1920,9500,1.0,0.0,0.0,...,7,1470,450.0,1966,0.0,98006,47.5683,-122.177,1820,10091
20037,8648900110,5/5/2014,555000.0,3,2.50,1940,3211,2.0,0.0,0.0,...,8,1940,0.0,2009,0.0,98027,47.5644,-122.093,1880,3078
20038,8648900110,8/26/2014,555000.0,3,2.50,1940,3211,2.0,0.0,0.0,...,8,1940,0.0,2009,0.0,98027,47.5644,-122.093,1880,3078
20164,7853400250,6/4/2014,610000.0,4,3.50,2910,5260,2.0,0.0,0.0,...,9,2910,0.0,2012,0.0,98065,47.5168,-121.883,2910,5260
20165,7853400250,2/19/2015,645000.0,4,3.50,2910,5260,2.0,0.0,0.0,...,9,2910,0.0,2012,0.0,98065,47.5168,-121.883,2910,5260
20596,2724049222,8/2/2014,163800.0,2,2.50,1000,1092,2.0,NaN,0.0,...,7,990,10.0,2004,0.0,98118,47.5419,-122.271,1330,1466
20597,2724049222,12/1/2014,220000.0,2,2.50,1000,1092,2.0,0.0,0.0,...,7,990,10.0,2004,0.0,98118,47.5419,-122.271,1330,1466
20653,8564860270,7/8/2014,449990.0,4,2.50,2680,5539,2.0,0.0,0.0,...,8,2680,0.0,2013,0.0,98045,47.4759,-121.734,2680,5992
20654,8564860270,3/30/2015,502000.0,4,2.50,2680,5539,2.0,NaN,0.0,...,8,2680,0.0,2013,0.0,98045,47.4759,-121.734,2680,5992
20763,6300000226,6/26/2014,240000.0,4,1.00,1200,2171,1.5,0.0,0.0,...,7,1200,0.0,1933,0.0,98133,47.7076,-122.342,1130,1598
20764,6300000226,5/4/2015,380000.0,4,1.00,1200,2171,1.5,0.0,0.0,...,7,1200,0.0,1933,0.0,98133,47.7076,-122.342,1130,1598
21564,7853420110,10/3/2014,594866.0,3,3.00,2780,6000,2.0,0.0,0.0,...,9,2780,0.0,2013,0.0,98065,47.5184,-121.886,2850,6000
21565,7853420110,5/4/2015,625000.0,3,3.00,2780,6000,2.0,0.0,0.0,...,9,2780,0.0,2013,NaN,98065,47.5184,-121.886,2850,6000

In [14]:
df.loc[df['id'].duplicated(keep = False) & df['date'].duplicated(keep = False)]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
93,6021501535,7/25/2014,430000.0,3,1.50,1580,5000,1.0,0.0,0.0,...,8,1290,290.0,1939,0.0,98117,47.6870,-122.386,1570,4500
94,6021501535,12/23/2014,700000.0,3,1.50,1580,5000,1.0,0.0,0.0,...,8,1290,290.0,1939,0.0,98117,47.6870,-122.386,1570,4500
313,4139480200,6/18/2014,1380000.0,4,3.25,4290,12103,1.0,0.0,3.0,...,11,2690,1600.0,1997,0.0,98006,47.5503,-122.102,3860,11244
314,4139480200,12/9/2014,1400000.0,4,3.25,4290,12103,1.0,0.0,3.0,...,11,2690,1600.0,1997,0.0,98006,47.5503,-122.102,3860,11244
324,7520000520,9/5/2014,232000.0,2,1.00,1240,12092,1.0,NaN,0.0,...,6,960,280.0,1922,1984.0,98146,47.4957,-122.352,1820,7460
325,7520000520,3/11/2015,240500.0,2,1.00,1240,12092,1.0,0.0,0.0,...,6,960,280.0,1922,1984.0,98146,47.4957,-122.352,1820,7460
345,3969300030,7/23/2014,165000.0,4,1.00,1000,7134,1.0,0.0,0.0,...,6,1000,0.0,1943,0.0,98178,47.4897,-122.240,1020,7138
346,3969300030,12/29/2014,239900.0,4,1.00,1000,7134,1.0,0.0,0.0,...,6,1000,0.0,1943,NaN,98178,47.4897,-122.240,1020,7138
371,2231500030,10/1/2014,315000.0,4,2.25,2180,10754,1.0,NaN,0.0,...,7,1100,1080.0,1954,0.0,98133,47.7711,-122.341,1810,6929
372,2231500030,3/24/2015,530000.0,4,2.25,2180,10754,1.0,0.0,0.0,...,7,1100,1080.0,1954,0.0,98133,47.7711,-122.341,1810,6929
717,8820903380,7/28/2014,452000.0,6,2.25,2660,13579,2.0,0.0,0.0,...,7,2660,0.0,1937,1990.0,98125,47.7142,-122.286,1120,8242
718,8820903380,1/2/2015,730000.0,6,2.25,2660,13579,2.0,0.0,0.0,...,7,2660,0.0,1937,1990.0,98125,47.7142,-122.286,1120,8242
823,726049190,10/2/2014,287500.0,3,1.00,1810,7200,1.0,0.0,0.0,...,7,1130,680.0,1954,0.0,98133,47.7493,-122.351,1810,8100
824,726049190,2/18/2015,431000.0,3,1.00,1810,7200,1.0,NaN,0.0,...,7,1130,680.0,1954,0.0,98133,47.7493,-122.351,1810,8100
836,8682262400,7/18/2014,430000.0,2,1.75,1350,4003,1.0,0.0,0.0,...,8,1350,0.0,2004,0.0,98053,47.7176,-122.033,1350,4479
837,8682262400,5/13/2015,419950.0,2,1.75,1350,4003,1.0,0.0,0.0,...,8,1350,0.0,2004,0.0,98053,47.7176,-122.033,1350,4479
1084,9834200885,7/17/2014,360000.0,4,2.50,2080,4080,1.0,0.0,0.0,...,7,1040,1040.0,1962,0.0,98144,47.5720,-122.290,1340,4080
1085,9834200885,4/20/2015,550000.0,4,2.50,2080,4080,1.0,0.0,0.0,...,7,1040,1040.0,1962,0.0,98144,47.5720,-122.290,1340,4080
1127,8062900070,9/9/2014,272000.0,5,1.50,2550,6300,1.0,0.0,0.0,...,7,1560,990.0,1959,0.0,98056,47.5014,-122.172,1380,6300
1128,8062900070,2/13/2015,369000.0,5,1.50,2550,6300,1.0,0.0,0.0,...,7,1560,990.0,1959,NaN,98056,47.5014,-122.172,1380,6300
1200,1231000510,9/22/2014,263000.0,3,1.75,1490,3800,1.0,0.0,0.0,...,6,700,790.0,1913,0.0,98118,47.5554,-122.270,2180,4000
1201,1231000510,5/4/2015,510000.0,3,1.75,1490,3800,1.0,0.0,0.0,...,6,700,790.0,1913,0.0,98118,47.5554,-122.270,2180,4000
1232,6117501820,6/18/2014,250275.0,2,1.00,790,11234,1.0,0.0,0.0,...,6,790,0.0,1942,0.0,98166,47.4413,-122.349,1930,11871
1233,6117501820,4/28/2015,435000.0,2,1.00,790,11234,1.0,0.0,0.0,...,6,790,0.0,1942,0.0,98166,47.4413,-122.349,1930,11871
1448,2228900270,8/12/2014,215000.0,2,1.00,1010,6000,1.0,0.0,0.0,...,6,1010,0.0,1944,NaN,98133,47.7710,-122.353,1610,7313
1449,2228900270,2/12/2015,302000.0,2,1.00,1010,6000,1.0,NaN,0.0,...,6,1010,0.0,1944,0.0,98133,47.7710,-122.353,1610,7313
1462,3630120700,5/13/2014,757000.0,3,3.25,3190,5283,2.0,0.0,0.0,...,9,3190,0.0,2007,0.0,98029,47.5534,-122.002,2950,5198
1463,3630120700,1/7/2015,765000.0,3,3.25,3190,5283,2.0,0.0,0.0,...,9,3190,0.0,2007,0.0,98029,47.5534,-122.002,2950,5198
1574,7888000390,6/27/2014,140000.0,3,1.00,1060,7473,1.0,0.0,0.0,...,7,1060,0.0,1959,0.0,98198,47.3699,-122.309,1320,7912
1575,7888000390,4/1/2015,235000.0,3,1.00,1060,7473,1.0,0.0,0.0,...,7,1060,0.0,1959,NaN,98198,47.3699,-122.309,1320,7912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18219,6751300375,7/2/2014,415000.0,3,1.00,1520,9030,1.0,0.0,0.0,...,7,1520,0.0,1956,0.0,98007,47.5870,-122.134,1470,8712
18220,6751300375,10/16/2014,522500.0,3,1.00,1520,9030,1.0,0.0,0.0,...,7,1520,0.0,1956,NaN,98007,47.5870,-122.134,1470,8712
18549,7657000540,9/2/2014,165000.0,4,1.00,1220,7980,1.5,0.0,0.0,...,6,1220,0.0,1944,0.0,98178,47.4924,-122.237,1210,7920
18550,7657000540,3/4/2015,260000.0,4,1.00,1220,7980,1.5,0.0,0.0,...,6,1220,0.0,1944,0.0,98178,47.4924,-122.237,1210,7920
18688,3558900590,11/25/2014,360000.0,6,1.75,2230,10080,1.0,0.0,0.0,...,7,1390,840.0,1969,0.0,98034,47.7089,-122.201,2110,8475
18689,3558900590,3/24/2015,692500.0,6,1.75,2230,10080,1.0,0.0,0.0,...,7,1390,840.0,1969,0.0,98034,47.7089,-122.201,2110,8475
18690,8121100395,6/24/2014,425000.0,4,1.50,1600,6180,1.5,0.0,0.0,...,6,1600,0.0,1946,0.0,98118,47.5681,-122.285,1410,6180
18691,8121100395,3/11/2015,645000.0,4,1.50,1600,6180,1.5,0.0,0.0,...,6,1600,0.0,1946,0.0,98118,47.5681,-122.285,1410,6180
18747,3332000615,10/20/2014,310000.0,3,1.00,1330,3740,1.5,0.0,0.0,...,6,1330,0.0,1903,NaN,98118,47.5502,-122.274,1330,5053
18748,3332000615,4/22/2015,389000.0,3,1.00,1330,3740,1.5,NaN,0.0,...,6,1330,0.0,1903,0.0,98118,47.5502,-122.274,1330,5053
18976,7856400300,7/2/2014,1410000.0,2,2.50,3180,9400,2.0,0.0,4.0,...,10,2610,570.0,1985,0.0,98006,47.5617,-122.158,3760,9450
18977,7856400300,3/22/2015,1510000.0,2,2.50,3180,9400,2.0,0.0,4.0,...,10,2610,570.0,1985,0.0,98006,47.5617,-122.158,3760,9450
19194,1901600090,6/26/2014,359000.0,5,1.75,1940,6654,1.5,0.0,0.0,...,7,1940,0.0,1953,0.0,98166,47.4663,-122.359,2300,9500
19195,1901600090,4/26/2015,390000.0,5,1.75,1940,6654,1.5,NaN,0.0,...,7,1940,0.0,1953,0.0,98166,47.4663,-122.359,2300,9500
19320,6021500970,5/28/2014,345000.0,2,1.00,1080,4000,1.0,0.0,0.0,...,7,1080,0.0,1940,0.0,98117,47.6902,-122.387,1530,4240
19321,6021500970,4/7/2015,874950.0,2,1.00,1080,4000,1.0,0.0,0.0,...,7,1080,?,1940,NaN,98117,47.6902,-122.387,1530,4240
19536,643300040,11/4/2014,481000.0,4,1.75,1920,9500,1.0,0.0,0.0,...,7,1470,450.0,1966,0.0,98006,47.5683,-122.177,1820,10091
19537,643300040,3/13/2015,719521.0,4,1.75,1920,9500,1.0,0.0,0.0,...,7,1470,450.0,1966,0.0,98006,47.5683,-122.177,1820,10091
20037,8648900110,5/5/2014,555000.0,3,2.50,1940,3211,2.0,0.0,0.0,...,8,1940,0.0,2009,0.0,98027,47.5644,-122.093,1880,3078
20038,8648900110,8/26/2014,555000.0,3,2.50,1940,3211,2.0,0.0,0.0,...,8,1940,0.0,2009,0.0,98027,47.5644,-122.093,1880,3078
20164,7853400250,6/4/2014,610000.0,4,3.50,2910,5260,2.0,0.0,0.0,...,9,2910,0.0,2012,0.0,98065,47.5168,-121.883,2910,5260
20165,7853400250,2/19/2015,645000.0,4,3.50,2910,5260,2.0,0.0,0.0,...,9,2910,0.0,2012,0.0,98065,47.5168,-121.883,2910,5260
20596,2724049222,8/2/2014,163800.0,2,2.50,1000,1092,2.0,NaN,0.0,...,7,990,10.0,2004,0.0,98118,47.5419,-122.271,1330,1466
20597,2724049222,12/1/2014,220000.0,2,2.50,1000,1092,2.0,0.0,0.0,...,7,990,10.0,2004,0.0,98118,47.5419,-122.271,1330,1466
20653,8564860270,7/8/2014,449990.0,4,2.50,2680,5539,2.0,0.0,0.0,...,8,2680,0.0,2013,0.0,98045,47.4759,-121.734,2680,5992
20654,8564860270,3/30/2015,502000.0,4,2.50,2680,5539,2.0,NaN,0.0,...,8,2680,0.0,2013,0.0,98045,47.4759,-121.734,2680,5992
20763,6300000226,6/26/2014,240000.0,4,1.00,1200,2171,1.5,0.0,0.0,...,7,1200,0.0,1933,0.0,98133,47.7076,-122.342,1130,1598
20764,6300000226,5/4/2015,380000.0,4,1.00,1200,2171,1.5,0.0,0.0,...,7,1200,0.0,1933,0.0,98133,47.7076,-122.342,1130,1598
21564,7853420110,10/3/2014,594866.0,3,3.00,2780,6000,2.0,0.0,0.0,...,9,2780,0.0,2013,0.0,98065,47.5184,-121.886,2850,6000
21565,7853420110,5/4/2015,625000.0,3,3.00,2780,6000,2.0,0.0,0.0,...,9,2780,0.0,2013,NaN,98065,47.5184,-121.886,2850,6000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 21 columns):
id               21597 non-null int64
date             21597 non-null object
price            21597 non-null float64
bedrooms         21597 non-null int64
bathrooms        21597 non-null float64
sqft_living      21597 non-null int64
sqft_lot         21597 non-null int64
floors           21597 non-null float64
waterfront       19221 non-null float64
view             21534 non-null float64
condition        21597 non-null int64
grade            21597 non-null int64
sqft_above       21597 non-null int64
sqft_basement    21597 non-null object
yr_built         21597 non-null int64
yr_renovated     17755 non-null float64
zipcode          21597 non-null int64
lat              21597 non-null float64
long             21597 non-null float64
sqft_living15    21597 non-null int64
sqft_lot15       21597 non-null int64
dtypes: float64(8), int64(11), object(2)
memory usage: 3.5+ MB